### ISSUE TITLE
How to remove a mention after it has been added?

### ISSUE THREAD

**Issue by malhayek2014** [CogniStreamer/tinyMCE-mention#16]
@StevenDevoogh 
I need to store all the mentioned users in a database. In my source method I have added a name and an id.  When a user submits a form I want to be able to get a list of all the ids that have been added in the text (can have more than one user)

My first thought was to use the insert method and track the id in hidden input "comma separated" and then parse the string on the form submit. The only thing that I am not sure on how to handle is how to delete a mention. If I mentioned @tinyMCE while typing and then I deleted @tinyMCE then added @tinyMCE-mention I need to remove the first mention from the list as the user remove their name from the mention list.

is there a better approach to what I am doing?
How can I do this?
is there a delete method? 

here is my code

	  tinymce.init({
		selector: "textarea#notes",
		theme: "modern",
		height: 300,
		schema: "html5",
		mentions: {
			source: function (query, process, delimiter) {
				
				$.ajax({	
					type: 'POST',
					url: '../../ajax/get-users.php',		
					data: {name: query},
					dataType: 'json',
					cache: false,
					timeout: 30000,
					success: function(data) { 			
						process(data);
					}
				});	
			}
		},
		plugins: [
			 "advlist autolink mention link image lists charmap print preview hr anchor pagebreak spellchecker ",
			 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime nonbreaking",
			 "save table contextmenu directionality emoticons template paste textcolor"
	   ],
	   content_css : "../../js/tinymce/skins/lightgray/mycontent.min.css",
	   theme_advanced_font_sizes: "10px,12px,13px,14px,16px,18px,20px",
	   font_size_style_values : "10px,12px,13px,14px,16px,18px,20px",
	   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
	   style_formats: [
			{title: 'Bold text', inline: 'b'},
			{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
			{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
			{title: 'Example 1', inline: 'span', classes: 'example1'},
			{title: 'Example 2', inline: 'span', classes: 'example2'},
			{title: 'Table styles'},
			{title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
		]
	 });

**Comment by StevenDevooght** [comment]
A 'removed' event is currently missing from this plugin but is on the todo list.

For now what you can do is override the insert method and insert something like this [~MentionedUser]. On the server you should be able to parse all valid entries.

**Comment by malhayek2014** [comment]
Thank you. I have used your suggestion.

**Comment by manojdhiman** [comment]
@malhayek2014  i want to use the same . I want to store the mentions in the db . Can you show me how you did this ?? the source code. 
thanks

**Comment by StevenDevooght** [comment]
You can override the `insert` function:
```javascript
insert: function(item) {
    return '<a class="user-mention" href="/profile/"' + item.userId + '>' + item.name + '</a>';
}
```

On the server you can parse the incoming html and pull out all `user-mention` links.

**Comment by christophedebatz** [comment]
Hi, how about the remove event to remove the inserted li in only one step? thanks

**Comment by meeshh** [comment]
@christophedebatz did you find anything concerning the remove event by any chance?
