### ISSUE TITLE
Issue with Enter Key

### ISSUE THREAD

**Issue by masihur** [CogniStreamer/tinyMCE-mention#18]
Hi,

I have used your plugin it is very nice. I have a problem with this plugin. I used tinymce3.5 version and I could not used <p> tag into tinymce editor. I updated manully then if a user write some ting into editor and then press enter key then we enter a <br> tag insted of <p> tag (tiny mce default).
So in this case if we press enter without prees space button and then enter @ delimeter thane suggationbox not open. Mention plugin not work.

**Comment by StevenDevooght** [comment]
Development on older versions has stopped... However if I have time I'll have a look if I can reproduce the problem.

What browser and version are you using. If possible could you share a snippet of your code?
