### ISSUE TITLE
Multiple delimiters

### ISSUE THREAD

**Issue by rafaelcor** [CogniStreamer/tinyMCE-mention#2]
Hello,
I've a question, this plugin can use multiple delimiters?
For example '@' for people and '#' for a number?
Thanks

**Comment by jssisodiya** [comment]
@StevenDevooght 
We can fetch data based on the delimiter in **source** as shown in above snippet. But can we do the same in **render** and **insert** callbacks?. The use case is different layout based on delimiter ( anchor tags for '@' and image tags for ':' )

**Comment by StevenDevooght** [comment]
It's possible to access the delimiter in the **render** & **insert** callbacks using the following code:

```javascript
this.options.delimiter
```
