### ISSUE TITLE
Extend Tinymce to support mention plugin in joomla site

### ISSUE THREAD

**Issue by sneha27** [CogniStreamer/tinyMCE-mention#21]
Hello,

This is very awesome plugin, that works well when implemented independently.
But I just want a way out to add same for joomla sites for the default TinyMce editors.

Things that I have tried are:
- Added mention plugin at location: "media/editors/tinymce/jscripts/tiny_mce/plugins"
- And tried adding "tinymce.init({....." in tinymce.php at various events.. But no success.

Can you please help me, where am I going wrong.
Where do I add this code? And make it work throughout.. 
Would really appreciate your help..

**Comment by StevenDevooght** [comment]
Hi,

I don't have experience with joomla myself... However this line of [code](https://github.com/joomla/joomla-cms/blob/3.4.1/plugins/editors/tinymce/tinymce.php#L591)indicates that joomla has an extensibility point built-in for adding custom plugins.

**Comment by sneha27** [comment]
Thank you.. Trying out few things.
Hope that works.

**Comment by sneha27** [comment]
Hi,

I'm using tinyMCE v3.5.x, hence using plugin v1.0.0
Below is the code I have added on event tinyMCE.init({...
but cannot see any action nor errors.
Mention js is included too.

Below is the code, I'm adding. Could you suggest me the change?

selector:'iframe, textarea',
plugins : "advlink, paste, mention",
delimiter: '@',
mentions: {
	source: [
		{ name: 'Tyra Porcelli' }, 
		{ name: 'Brigid Reddish' },
		{ name: 'Ashely Buckler' },
		{ name: 'Teddy Whelan' }
	]
}

**Comment by StevenDevooght** [comment]
Hi,

Can you check if the plugin actually is loaded on the page?
![image](https://cloud.githubusercontent.com/assets/449346/8133632/cc46ca74-1129-11e5-9a7c-c50d0a45e2ba.png)

**Comment by sneha27** [comment]
Hello,

Thanks for your response.
Checked that.. Plugin/plugin file is loaded.
Going through, editor_plugin.js control. Hope that helps.
Tell me if any needful things are to be checked.

On Fri, Jun 12, 2015 at 9:09 PM, Steven Devooght <notifications@github.com>
wrote:

> Hi,
>
> Can you check if the plugin actually is loaded on the page?
> [image: image]
> <https://cloud.githubusercontent.com/assets/449346/8133632/cc46ca74-1129-11e5-9a7c-c50d0a45e2ba.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CogniStreamer/tinyMCE-mention/issues/21#issuecomment-111530972>
> .
>



-- 
Regards,
Sneha

**Comment by StevenDevooght** [comment]
First you can check if the developer tools throw an exception. 
If not, you can put a break-point in `editor_plugin` and check if it is hit.
