### ISSUE TITLE
Username show in start of editor if user select username from notification drop-down on the safari browser.

### ISSUE THREAD

**Issue by masihur** [CogniStreamer/tinyMCE-mention#22]
Hi,
I have used tinyMCE 3.5 version, I have integrated mention plug-in on it. I got an issue on the safari browser. If we write some text into the editor after that press @USERNAME then autosuggationbox open. If we select any username from the drop-down then it show into the start point (Left side) of the editor. While on another browser user-name show at correct position. Screen shot as below.

![first1](https://cloud.githubusercontent.com/assets/1920628/8129836/d8ef70cc-112a-11e5-828e-d319451b63d2.png)

After select user from drop-down

![second](https://cloud.githubusercontent.com/assets/1920628/8129842/e9ef192c-112a-11e5-8b3e-9e5891d84d14.png)

**Comment by StevenDevooght** [comment]
Hi,

Are you using safari on a mac?

**Comment by masihur** [comment]
Hi,

No I am using safari on Widow7.

**Comment by StevenDevooght** [comment]
I managed to reproduce the issue. Safari loses focus after calling `this.editor.dom.remove`. I tried a couple of things but didn't manage to get the correct behavior...

Since Apple ditched Safari for windows a couple of years ago I consider this issue as low priority.
