### ISSUE TITLE
is there a way to add "grouping" to the dropdown menu ?

### ISSUE THREAD

**Issue by ManuZenou** [CogniStreamer/tinyMCE-mention#24]

**Comment by StevenDevooght** [comment]
The `renderDropdown` & `render` function can be overridden as you like. I don't know if that will be enough for what you are trying to do...

**Comment by ManuZenou** [comment]
both function return HTML string. is there a way to override an event that invokes after it gets rendered ?
for example, I'd like to try and use Select2 (which has the functionality that I need), and I need to call the .select2() function.

**Comment by StevenDevooght** [comment]
There is currently no callback event after the dropdown is rendered. However the grouping can be easily done using just html and css I think.
