### ISSUE TITLE
Various sources

### ISSUE THREAD

**Issue by thibaultvanc** [CogniStreamer/tinyMCE-mention#28]
Is it possible to set various sources. For exemple, if I press # key I have a source1,  if I press @  key, i have the source 2 ??

Thanks in advance

**Comment by StevenDevooght** [comment]
Hi,

If you configure the source parameter [as a function](https://github.com/CogniStreamer/tinyMCE-mention#function) you can use the delimiter parameter to differentiate sources.

**Comment by thibaultvanc** [comment]
Thank You Steven, I have just tried. Its working with @ but not with #
is it normal ?

**Comment by StevenDevooght** [comment]
@thibaultvanc, can you create a sample fiddle (http://fiddle.tinymce.com/) that demonstrates this behavior?

**Comment by thibaultvanc** [comment]
The mention pluggin is not attached to the fiddle, and I don't know how to do it ...

**Comment by StevenDevooght** [comment]
I created a fiddle a while ago. You can have a look [here](http://fiddle.tinymce.com/EWeaab/1)

**Comment by thibaultvanc** [comment]
Here : http://fiddle.tinymce.com/hmfaab/7

**Comment by StevenDevooght** [comment]
I forgot to mention, but the delimiters have to be configured too. See the [updated sample](http://fiddle.tinymce.com/hmfaab/12)

**Comment by thibaultvanc** [comment]
Ok Thanks
but this one doesn't work ? ##

http://fiddle.tinymce.com/hmfaab/14

**Comment by StevenDevooght** [comment]
Currently only single character delimiters are supported... Also differentiating between '#' and '##' would not be possible.

**Comment by thibaultvanc** [comment]
ok thank You
