### ISSUE TITLE
How to get select event ?

### ISSUE THREAD

**Issue by pkgoyal86** [CogniStreamer/tinyMCE-mention#29]
How can I get select event when any value on suggestion is clicked, I want to save id of users in a hidden textfield to send notification.

**Comment by StevenDevooght** [comment]
A `selected` or `removed` event is not available in this plugin.

You can however override the insert function:
```javascript
insert: function(item) {
    return '<a class="user-mention" href="/profile/' + item.userId + '">' + item.name + '</a>';
}
```
On the server you can parse the incoming html and pull out all user-mention links.

**Comment by pkgoyal86** [comment]
Thanks :)

**Comment by pkgoyal86** [comment]
Hi Steven,

Thanks for this outstanding plugin. I am using it in my webapplication.

I want a little favor from you. How can I use it on simple textarea. Do you
have another plugin for simple textarea ?

If you have please suggest.

Thanks Again.

PK
